### ISSUE TITLE
Zope

### ISSUE THREAD

**Issue by t0mB1** [max-kov/pool#1]
In the file 'collisions', what version of Zope did you use and how did you install it?

**Comment by max-kov** [comment]
Hey @t0mB1 , sorry for the late reply. In theory, it shouldn't matter but I reinstalled the game with python 3.7 and zope.event-4.4, and it seemed to work fine.

**Comment by max-kov** [comment]
As for the installation - if you're running Linux, you can just run `./run.sh` and the script should install everything for you. [On windows](https://github.com/max-kov/pool#windows), I think you need to install pip and then you should be able to install the package by running `pip install zope.event` in the command line.
