### ISSUE TITLE
Make starting the game easy

### ISSUE THREAD

**Issue by kovalevvlad** [max-kov/pool#18]
Add a shell script to set up the virtual env and check for requirements (python/pip/virtualenv). Windows? Mac?

Can try docker but that will be a bit tricky with X-frowarding and you still have issues with windows and potentially mac.

Other options?

**Comment by max-kov** [comment]
How about a setup.py file? Python version check can be made like [this](https://stackoverflow.com/questions/19534896/enforcing-python-version-in-setup-py), also the script could run the included tests and check the required python libraries on install.

**Comment by max-kov** [comment]
Should work on all OSs as well.

**Comment by kovalevvlad** [comment]
Just create a shell script that creates a venv, installs all of the requirements and runs the thing

**Comment by max-kov** [comment]
Implemented in #14
